get:
  tags:
    - Applications
  description: This API endpoint lists a specific program
  operationId: RetrieveApplication
  parameters:
  - name: id
    in: path
    description: A unique integer value identifying this application.
    required: true
    style: simple
    explode: false
    schema:
      type: string
  responses:
    "200":
      content:
        application/json:
          schema:
            $ref: '../components/schemas/inline_responses/inline_response_200_7.yaml'
