post:
  tags:
    - Applications
  operationId: CreateApplicationResponseAttachment
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../components/schemas/body/body_36.yaml'
      application/x-www-form-urlencoded:
        schema:
          $ref: '../components/schemas/body/body_37.yaml'
      multipart/form-data:
        schema:
          $ref: '../components/schemas/body/body_38.yaml'
  responses:
    "200":
      content:
        application/json:
          schema:
            $ref: '../components/schemas/inline_responses/inline_response_200_14.yaml'
