put:
  tags:
    - Applications
  operationId: UpdateApplication
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../components/schemas/body/body_72.yaml'
      application/x-www-form-urlencoded:
        schema:
          $ref: '../components/schemas/body/body_73.yaml'
      multipart/form-data:
        schema:
          $ref: '../components/schemas/body/body_74.yaml'
  responses:
    "200":
      content:
        application/json:
          schema:
            $ref: '../components/schemas/inline_responses/inline_response_200_7.yaml'
